# Generated by Django 3.2.14 on 2022-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphqlsubscription',
            name='relay_id',
            field=models.CharField(max_length=36),
        ),
    ]
