# Generated by Django 3.1.7 on 2021-07-06 07:59

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210330_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=common.storages.UniqueFilePathGenerator('avatars')),
        ),
    ]
