# Generated by Django 3.1.7 on 2021-07-13 09:19

import common.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(null=True, upload_to=common.storages.UniqueFilePathGenerator('avatars'))),
                ('thumbnail', models.ImageField(null=True, upload_to=common.storages.UniqueFilePathGenerator('avatars/thumbnails'))),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='users.useravatar'),
        ),
    ]
