# Generated by Django 3.1.7 on 2021-07-14 08:22

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='original',
            field=models.ImageField(null=True, storage=common.storages.PublicS3Boto3StorageWithCDN, upload_to=common.storages.UniqueFilePathGenerator('avatars')),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='thumbnail',
            field=models.ImageField(null=True, storage=common.storages.PublicS3Boto3StorageWithCDN, upload_to=common.storages.UniqueFilePathGenerator('avatars/thumbnails')),
        ),
    ]
