export const ENV = {
  BASE_API_URL: process.env.REACT_APP_BASE_API_URL ?? '',
  SUBSCRIPTIONS_URL: process.env.REACT_APP_SUBSCRIPTIONS_URL ?? '',
  ENVIRONMENT_NAME: process.env.REACT_APP_ENVIRONMENT_NAME,
  SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
  WEB_APP_URL: process.env.REACT_APP_WEB_APP_URL ?? '',
  EMAIL_ASSETS_URL: process.env.REACT_APP_EMAIL_ASSETS_URL ?? '',
  PUBLIC_URL: process.env.PUBLIC_URL,
  CONTENTFUL_SPACE: process.env.REACT_APP_CONTENTFUL_SPACE,
  CONTENTFUL_ENV: process.env.REACT_APP_CONTENTFUL_ENV,
  CONTENTFUL_TOKEN: process.env.REACT_APP_CONTENTFUL_TOKEN,
  STRIPE_PUBLISHABLE_KEY: process.env.REACT_APP_STRIPE_PUBLISHABLE_KEY ?? '',
};
