# Generated by Django 3.1.7 on 2021-03-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0007_2_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.customer',),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.price',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.product',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.subscription',),
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.subscriptionitem',),
        ),
    ]
