import { TenantUserRole } from '@sb/webapp-api-client';
import { Link } from '@sb/webapp-core/components/buttons';
import { PageLayout } from '@sb/webapp-core/components/pageLayout';
import { Paragraph } from '@sb/webapp-core/components/typography';
import { Alert, AlertDescription, AlertTitle } from '@sb/webapp-core/components/ui/alert';
import { Button } from '@sb/webapp-core/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@sb/webapp-core/components/ui/card';
import { useGenerateLocalePath } from '@sb/webapp-core/hooks';
import { TenantRoleAccess } from '@sb/webapp-tenants/components/tenantRoleAccess';
import { useGenerateTenantPath } from '@sb/webapp-tenants/hooks';
import { AlertCircle, ArrowUpRight, BookOpen, Github, Sparkles } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { FormattedMessage, useIntl } from 'react-intl';

import { RoutesConfig } from '../../app/config/routes';

type DashboardItem = {
  title: string;
  subtitle: string;
  link: string;
  roleAccess?: TenantUserRole[];
};

export const Home = () => {
  const intl = useIntl();
  const generateLocalePath = useGenerateLocalePath();
  const generateTenantPath = useGenerateTenantPath();

  const dashboardItems: DashboardItem[] = [
    {
      title: intl.formatMessage({
        defaultMessage: 'Payments',
        id: 'Home / Payments / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Example of single payment form.',
        id: 'Home / Payments / Subtitle',
      }),
      link: generateTenantPath(RoutesConfig.finances.paymentConfirm),
      roleAccess: [TenantUserRole.OWNER, TenantUserRole.ADMIN],
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Subscriptions',
        id: 'Home / Subscriptions / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Example of subscription management.',
        id: 'Home / Subscriptions / Subtitle',
      }),
      link: generateTenantPath(RoutesConfig.subscriptions.index),
      roleAccess: [TenantUserRole.OWNER, TenantUserRole.ADMIN],
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Open AI integration',
        id: 'Home / Open AI / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'SaaS ideas generator as an example of Open AI integration.',
        id: 'Home / Open AI / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.saasIdeas),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Content items',
        id: 'Home / CMD items / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Demo of the Contentful integration.',
        id: 'Home / CMD items / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.demoItems),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Documents',
        id: 'Home / Documents / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'File upload and asset management example.',
        id: 'Home / Documents / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.documents),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'CRUD',
        id: 'Home / CRUD / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Create-Read-Update-Delete module example that is generated by built-in generator.',
        id: 'Home / CRUD / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.crudDemoItem.list),
    },
  ];

  const renderItem = (item: DashboardItem, key: number) => (
    <TenantRoleAccess allowedRoles={item.roleAccess} key={key}>
      <Link navLink to={item.link} className="group block h-full">
        <Card className="h-full transition-all duration-200 hover:shadow-md hover:border-primary/50">
          <CardHeader className="pb-3">
            <div className="flex items-start justify-between">
              <CardTitle className="text-lg font-semibold">{item.title}</CardTitle>
              <ArrowUpRight className="h-5 w-5 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" />
            </div>
          </CardHeader>
          <CardContent>
            <CardDescription className="text-sm leading-relaxed">{item.subtitle}</CardDescription>
          </CardContent>
        </Card>
      </Link>
    </TenantRoleAccess>
  );

  return (
    <PageLayout>
      <Helmet
        title={intl.formatMessage({
          defaultMessage: 'Homepage',
          id: 'Home / page title',
        })}
      />

      <div className="mx-auto w-full max-w-5xl space-y-8">
        {/* Hero Section */}
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-primary" />
            <h1 className="text-3xl font-bold tracking-tight">
              <FormattedMessage defaultMessage="Dashboard" id="Home / header" />
            </h1>
          </div>
          <Paragraph className="text-lg text-muted-foreground">
            <FormattedMessage
              defaultMessage="Welcome! You're viewing your personal application dashboard example."
              id="Home / subheading"
            />
          </Paragraph>
        </div>

        {/* Quick Actions */}
        <div className="flex flex-wrap gap-3">
          <Button
            variant="outline"
            size="lg"
            asChild
            className="gap-2"
          >
            <a
              href="https://github.com/apptension/saas-boilerplate"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center"
            >
              <Github className="h-4 w-4" />
              <span>GitHub Repository</span>
              <ArrowUpRight className="h-3 w-3" />
            </a>
          </Button>
          <Button
            variant="outline"
            size="lg"
            asChild
            className="gap-2"
          >
            <a
              href="https://docs.demo.saas.apptoku.com/"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center"
            >
              <BookOpen className="h-4 w-4" />
              <span>Documentation</span>
              <ArrowUpRight className="h-3 w-3" />
            </a>
          </Button>
        </div>

        {/* Info Alert */}
        <Alert variant="info" className="border-blue-700/20 bg-blue-50 dark:bg-blue-950/20">
          <AlertCircle className="h-4 w-4 text-blue-700" />
          <AlertTitle className="text-base font-semibold text-blue-900 dark:text-blue-100">Heads up!</AlertTitle>
          <AlertDescription className="mt-2 space-y-3 text-sm text-blue-800 dark:text-blue-200">
            <p>
              Each feature you see here is a module demonstrating the versatility and usability of the SaaS Boilerplate.
              Please remember, these modules are simply examples. You are encouraged to customize, adjust, and modify each
              module to best fit your application's needs.
            </p>
            <p className="font-medium">Remember, the SaaS Boilerplate is your starting point - make it your own!</p>
          </AlertDescription>
        </Alert>

        {/* Features Grid */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold tracking-tight">Available Features</h2>
          <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
            {dashboardItems.map((item, key) => renderItem(item, key))}
          </div>
        </div>
      </div>
    </PageLayout>
  );
};
