import { TenantUserRole } from '@sb/webapp-api-client';
import { Link } from '@sb/webapp-core/components/buttons';
import { PageLayout } from '@sb/webapp-core/components/pageLayout';
import { Paragraph } from '@sb/webapp-core/components/typography';
import { Alert, AlertDescription, AlertTitle } from '@sb/webapp-core/components/ui/alert';
import { Button } from '@sb/webapp-core/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@sb/webapp-core/components/ui/card';
import { useGenerateLocalePath } from '@sb/webapp-core/hooks';
import { TenantRoleAccess } from '@sb/webapp-tenants/components/tenantRoleAccess';
import { useGenerateTenantPath } from '@sb/webapp-tenants/hooks';
import {
  AlertCircle,
  ArrowUpRight,
  BookOpen,
  Code2,
  ExternalLink,
  Github,
  Rocket,
  Server,
  Shield,
  Sparkles,
} from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { FormattedMessage, useIntl } from 'react-intl';

import { RoutesConfig } from '../../app/config/routes';

type DashboardItem = {
  title: string;
  subtitle: string;
  link: string;
  roleAccess?: TenantUserRole[];
};

export const Home = () => {
  const intl = useIntl();
  const generateLocalePath = useGenerateLocalePath();
  const generateTenantPath = useGenerateTenantPath();

  const dashboardItems: DashboardItem[] = [
    {
      title: intl.formatMessage({
        defaultMessage: 'Payments',
        id: 'Home / Payments / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Example of single payment form.',
        id: 'Home / Payments / Subtitle',
      }),
      link: generateTenantPath(RoutesConfig.finances.paymentConfirm),
      roleAccess: [TenantUserRole.OWNER, TenantUserRole.ADMIN],
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Subscriptions',
        id: 'Home / Subscriptions / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Example of subscription management.',
        id: 'Home / Subscriptions / Subtitle',
      }),
      link: generateTenantPath(RoutesConfig.subscriptions.index),
      roleAccess: [TenantUserRole.OWNER, TenantUserRole.ADMIN],
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Open AI integration',
        id: 'Home / Open AI / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'SaaS ideas generator as an example of Open AI integration.',
        id: 'Home / Open AI / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.saasIdeas),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Content items',
        id: 'Home / CMD items / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Demo of the Contentful integration.',
        id: 'Home / CMD items / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.demoItems),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'Documents',
        id: 'Home / Documents / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'File upload and asset management example.',
        id: 'Home / Documents / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.documents),
    },
    {
      title: intl.formatMessage({
        defaultMessage: 'CRUD',
        id: 'Home / CRUD / Title',
      }),
      subtitle: intl.formatMessage({
        defaultMessage: 'Create-Read-Update-Delete module example that is generated by built-in generator.',
        id: 'Home / CRUD / Subtitle',
      }),
      link: generateLocalePath(RoutesConfig.crudDemoItem.list),
    },
  ];

  const renderItem = (item: DashboardItem, key: number) => (
    <TenantRoleAccess allowedRoles={item.roleAccess} key={key}>
      <Link navLink to={item.link} className="group block h-full">
        <Card className="h-full transition-all duration-200 hover:border-primary/50 hover:shadow-md">
          <CardHeader className="pb-3">
            <div className="flex items-start justify-between">
              <CardTitle className="text-lg font-semibold">{item.title}</CardTitle>
              <ArrowUpRight className="h-5 w-5 text-muted-foreground transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" />
            </div>
          </CardHeader>
          <CardContent>
            <CardDescription className="text-sm leading-relaxed">{item.subtitle}</CardDescription>
          </CardContent>
        </Card>
      </Link>
    </TenantRoleAccess>
  );

  return (
    <PageLayout>
      <Helmet
        title={intl.formatMessage({
          defaultMessage: 'Homepage',
          id: 'Home / page title',
        })}
      />

      <div className="mx-auto w-full max-w-7xl space-y-8">
        {/* Hero Section */}
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-primary" />
            <h1 className="text-3xl font-bold tracking-tight">
              <FormattedMessage defaultMessage="Dashboard" id="Home / header" />
            </h1>
          </div>
          <Paragraph className="text-lg text-muted-foreground">
            <FormattedMessage
              defaultMessage="Welcome! You're viewing your personal application dashboard example."
              id="Home / subheading"
            />
          </Paragraph>
        </div>

        {/* Quick Actions */}
        <div className="flex flex-wrap gap-3">
          <Button variant="outline" size="lg" asChild className="gap-2">
            <a
              href="https://github.com/apptension/saas-boilerplate"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center"
            >
              <Github className="h-4 w-4" />
              <span>GitHub Repository</span>
              <ArrowUpRight className="h-3 w-3" />
            </a>
          </Button>
          <Button variant="outline" size="lg" asChild className="gap-2">
            <a
              href="https://docs.demo.saas.apptoku.com/"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center"
            >
              <BookOpen className="h-4 w-4" />
              <span>Documentation</span>
              <ArrowUpRight className="h-3 w-3" />
            </a>
          </Button>
        </div>

        {/* Two Column Layout */}
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
          {/* Getting Started Section - Takes 2 columns on large screens */}
          <div className="space-y-6 lg:col-span-2">
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <Rocket className="h-5 w-5 text-primary" />
                <h2 className="text-2xl font-semibold tracking-tight">
                  {intl.formatMessage({
                    defaultMessage: 'Getting Started',
                    id: 'Home / Getting Started / Title',
                  })}
                </h2>
              </div>
              <Paragraph className="text-muted-foreground">
                {intl.formatMessage({
                  defaultMessage: 'Follow these steps to start developing with the SaaS Boilerplate.',
                  id: 'Home / Getting Started / Subtitle',
                })}
              </Paragraph>
            </div>

            <div className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <Code2 className="h-5 w-5 text-primary" />
                    {intl.formatMessage({
                      defaultMessage: 'Development Commands',
                      id: 'Home / Development Commands / Title',
                    })}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-muted-foreground">
                      {intl.formatMessage({
                        defaultMessage: 'Generate Code',
                        id: 'Home / Development Commands / Generate',
                      })}
                    </p>
                    <div className="space-y-1">
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm plop</code>
                      <p className="text-xs text-muted-foreground">
                        {intl.formatMessage({
                          defaultMessage: 'Generate components, CRUD modules, hooks, emails, and more (run from packages/webapp)',
                          id: 'Home / Development Commands / Plop Description',
                        })}
                      </p>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-muted-foreground">
                      {intl.formatMessage({
                        defaultMessage: 'Database',
                        id: 'Home / Development Commands / Database',
                      })}
                    </p>
                    <div className="space-y-1">
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">
                        pnpm saas backend makemigrations
                      </code>
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm saas backend migrate</code>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-muted-foreground">
                      {intl.formatMessage({
                        defaultMessage: 'Testing & Quality',
                        id: 'Home / Development Commands / Testing',
                      })}
                    </p>
                    <div className="space-y-1">
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm saas backend test</code>
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm saas test</code>
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm saas lint</code>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <p className="text-sm font-semibold text-muted-foreground">
                      {intl.formatMessage({
                        defaultMessage: 'Tools',
                        id: 'Home / Development Commands / Tools',
                      })}
                    </p>
                    <div className="space-y-1">
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">
                        pnpm nx run webapp:storybook
                      </code>
                      <p className="text-xs text-muted-foreground">
                        {intl.formatMessage({
                          defaultMessage: 'Run Storybook on port 5002',
                          id: 'Home / Development Commands / Storybook Description',
                        })}
                      </p>
                      <code className="block rounded-md bg-muted px-3 py-2 text-sm">pnpm saas backend shell</code>
                      <p className="text-xs text-muted-foreground">
                        {intl.formatMessage({
                          defaultMessage: 'Access backend shell for advanced operations',
                          id: 'Home / Development Commands / Shell Description',
                        })}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <Shield className="h-5 w-5 text-primary" />
                    {intl.formatMessage({
                      defaultMessage: 'Admin Panel',
                      id: 'Home / Admin Panel / Title',
                    })}
                  </CardTitle>
                  <CardDescription>
                    {intl.formatMessage({
                      defaultMessage:
                        'Access the Django admin interface for managing data and performing administrative tasks',
                      id: 'Home / Admin Panel / Description',
                    })}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="space-y-2">
                    <p className="text-sm font-medium">
                      {intl.formatMessage({
                        defaultMessage: 'Access URL',
                        id: 'Home / Admin Panel / URL Label',
                      })}
                    </p>
                    <a
                      href="http://admin.localhost:5001"
                      target="_blank"
                      rel="noreferrer"
                      className="inline-flex items-center gap-2 text-sm text-primary hover:underline"
                    >
                      <code className="rounded-md bg-muted px-3 py-1.5 font-mono text-sm">
                        http://admin.localhost:5001
                      </code>
                      <ExternalLink className="h-4 w-4" />
                    </a>
                  </div>

                  <div className="space-y-3">
                    <p className="text-sm font-medium">
                      {intl.formatMessage({
                        defaultMessage: 'Login Credentials',
                        id: 'Home / Admin Panel / Credentials Title',
                      })}
                    </p>
                    <dl className="space-y-3">
                      <div>
                        <dt className="mb-1 text-xs font-medium text-muted-foreground">
                          {intl.formatMessage({
                            defaultMessage: 'Email',
                            id: 'Home / Admin Panel / Email Label',
                          })}
                        </dt>
                        <dd className="flex items-center gap-2">
                          <code className="rounded-md bg-muted px-2.5 py-1.5 font-mono text-sm">admin@example.com</code>
                          <span className="text-xs text-muted-foreground">
                            {intl.formatMessage({
                              defaultMessage: 'or set ADMIN_EMAIL in .env',
                              id: 'Home / Admin Panel / Email Note',
                            })}
                          </span>
                        </dd>
                      </div>
                      <div>
                        <dt className="mb-1 text-xs font-medium text-muted-foreground">
                          {intl.formatMessage({
                            defaultMessage: 'Password',
                            id: 'Home / Admin Panel / Password Label',
                          })}
                        </dt>
                        <dd className="flex items-center gap-2">
                          <code className="rounded-md bg-muted px-2.5 py-1.5 font-mono text-sm">AvPZpabgj9Z8</code>
                          <span className="text-xs text-muted-foreground">
                            {intl.formatMessage({
                              defaultMessage: 'or set ADMIN_DEFAULT_PASSWORD in .env',
                              id: 'Home / Admin Panel / Password Note',
                            })}
                          </span>
                        </dd>
                      </div>
                    </dl>
                  </div>

                  <Alert variant="default" className="mt-4">
                    <AlertCircle className="h-4 w-4" />
                    <AlertDescription className="text-sm">
                      {intl.formatMessage({
                        defaultMessage:
                          'These credentials are for local development only. Always use strong, unique passwords in production!',
                        id: 'Home / Admin Panel / Security Warning',
                      })}
                    </AlertDescription>
                  </Alert>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <Server className="h-5 w-5 text-primary" />
                    {intl.formatMessage({
                      defaultMessage: 'Local Services',
                      id: 'Home / Local Services / Title',
                    })}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="space-y-2 text-sm">
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Web App</span>
                      <a
                        href="http://localhost:3000"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:3000</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Backend API</span>
                      <a
                        href="http://localhost:5001"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:5001</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Workers Trigger</span>
                      <a
                        href="http://localhost:3005"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:3005</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Mailcatcher</span>
                      <a
                        href="http://localhost:1080"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:1080</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Documentation</span>
                      <a
                        href="http://localhost:3006"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:3006</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Flower (Celery)</span>
                      <a
                        href="http://localhost:5555"
                        target="_blank"
                        rel="noreferrer"
                        className="flex items-center gap-1 text-primary hover:underline"
                      >
                        <code className="text-xs">localhost:5555</code>
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Info Alert */}
              <Alert variant="info" className="border-blue-700/20 bg-blue-50 dark:bg-blue-950/20">
                <AlertCircle className="h-4 w-4 text-blue-700" />
                <AlertTitle className="text-base font-semibold text-blue-900 dark:text-blue-100">
                  {intl.formatMessage({
                    defaultMessage: 'Heads up!',
                    id: 'Home / Alert / Title',
                  })}
                </AlertTitle>
                <AlertDescription className="mt-2 space-y-3 text-sm text-blue-800 dark:text-blue-200">
                  <p>
                    {intl.formatMessage({
                      defaultMessage:
                        "Each feature you see here is a module demonstrating the versatility and usability of the SaaS Boilerplate. Please remember, these modules are simply examples. You are encouraged to customize, adjust, and modify each module to best fit your application's needs.",
                      id: 'Home / Alert / Description',
                    })}
                  </p>
                  <p className="font-medium">
                    {intl.formatMessage({
                      defaultMessage: 'Remember, the SaaS Boilerplate is your starting point - make it your own!',
                      id: 'Home / Alert / Call to Action',
                    })}
                  </p>
                </AlertDescription>
              </Alert>
            </div>
          </div>

          {/* Available Features Section - Takes 1 column on large screens */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              <h2 className="text-2xl font-semibold tracking-tight">
                {intl.formatMessage({
                  defaultMessage: 'Available Features',
                  id: 'Home / Features / Title',
                })}
              </h2>
            </div>
            <div className="grid w-full grid-cols-1 gap-4">
              {dashboardItems.map((item, key) => renderItem(item, key))}
            </div>
          </div>
        </div>
      </div>
    </PageLayout>
  );
};
