# Generated by Django 4.2 on 2024-03-26 12:10

from django.db import migrations, models
import django.db.models.deletion

from apps.multitenancy.constants import TenantType


def populate_tenant(apps, schema_editor):
    CrudDemoItem = apps.get_model('demo', 'CrudDemoItem')
    Tenant = apps.get_model('multitenancy', 'Tenant')

    for item in CrudDemoItem.objects.all():
        if not item.tenant:
            default_tenant = Tenant.objects.filter(type=TenantType.DEFAULT, creator=item.created_by).first()
            item.tenant = default_tenant
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0005_tenant_billing_email'),
        ('demo', '0002_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='cruddemoitem',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_set',
                to='multitenancy.tenant',
                verbose_name='Tenant',
            ),
        ),
        migrations.RunPython(populate_tenant, reverse_code=migrations.RunPython.noop),
    ]
