# Generated by Django 5.0.6 on 2025-02-11 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demo', '0003_cruddemoitem_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruddemoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruddemoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
