[tool.black]
line-length = 120
skip-string-normalization = true
exclude = "/(.git|.serverless|node_modules|data|__pypackages__)/"
target-versions = "py311"

[tool.ruff]
select = ["E", "F", "B", "S", "A", "C40", "DJ", "PIE", "T20", "SIM", "PLR"]
ignore = ["S101", "A003", "S105", "SIM105", "A002", "B904", "PLR0913"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["E", "F", "C4", "PIE", "RET", "SIM", "PLR"]
unfixable = ["B"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
    "libs",
    "docs",
    "data",
    "test_*.py"
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]

[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.dev-dependencies]
dev = [
    "black~=22.12",
    "moto~=4.1",
    "pytest~=7.2",
    "pytest-mock~=3.10",
    "pytest-factoryboy~=2.5",
    "pytest-dotenv~=0.5",
    "python-dotenv~=0.21",
    "pytest-cov~=4.0",
    "ruff>=0.0.261",
]

[tool.setuptools]
py-modules = []

[project]
name = "sb_workers"
version = "1.0.0"
description = ""

dependencies = [
    "boto3~=1.26",
    "pyjwt~=2.6",
    "hashids~=1.3",
    "contentful~=1.13",
    "environs~=9.5",
    "psycopg2-binary~=2.9",
    "sentry-sdk~=1.14",
    "sqlalchemy~=2.0",
    "pydantic~=1.10.4",
    "pytest-freezegun>=0.4.2",
]
requires-python = "~=3.11.0"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

