# Generated by Django 3.1.7 on 2021-06-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_cruddemoitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruddemoitem',
            old_name='user',
            new_name='created_by',
        ),
    ]
