import { color } from '@oclif/color';
import { existsSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import * as crypto from 'crypto';

import { BaseCommand } from '../../baseCommand';
import { input, confirm } from '../../lib/prompts';
import { getPlatformConfig, updatePlatformConfig, VPSConfig } from '../../config/platform';
import { getRootPath } from '../../config/env';

export default class VPSSetup extends BaseCommand<typeof VPSSetup> {
  static description = 'Configure VPS deployment settings';

  static examples = ['<%= config.bin %> <%= command.id %>'];

  async run(): Promise<void> {
    this.log(color.blue('\n🖥️  VPS Deployment Setup\n'));

    const existingConfig = await getPlatformConfig();

    if (existingConfig.vps?.host) {
      const overwrite = await confirm({
        message: `VPS is configured (${existingConfig.vps.host}). Reconfigure?`,
        default: false,
      });

      if (!overwrite) {
        this.log('Setup cancelled.');
        return;
      }
    }

    this.log(color.bold('Step 1: VPS Connection\n'));

    const host = await input({
      message: 'VPS hostname or IP:',
      validate: (v) => v ? true : 'Required',
    });

    const user = await input({
      message: 'SSH username:',
      default: 'root',
    });

    const port = await input({
      message: 'SSH port:',
      default: '22',
      validate: (v) => {
        const n = parseInt(v, 10);
        return !isNaN(n) && n > 0 && n < 65536 ? true : 'Invalid port';
      },
    });

    const defaultKey = resolve(process.env.HOME || '', '.ssh', 'id_rsa');
    const privateKeyPath = await input({
      message: 'SSH private key path:',
      default: existsSync(defaultKey) ? defaultKey : '~/.ssh/id_rsa',
    });

    const deployPath = await input({
      message: 'Deploy directory on VPS:',
      default: '/opt/saas-app',
    });

    const vpsConfig: VPSConfig = {
      host,
      user,
      port: parseInt(port, 10),
      privateKeyPath,
      deployPath,
    };

    await updatePlatformConfig({ vps: vpsConfig });
    this.log(color.green('\n✓ VPS connection saved\n'));

    // Generate docker-compose
    const generateCompose = await confirm({
      message: 'Generate docker-compose.prod.yml?',
      default: true,
    });

    if (generateCompose) {
      const domain = await input({
        message: 'Your domain (e.g., example.com):',
        validate: (v) => v && v.includes('.') ? true : 'Enter a valid domain',
      });

      const email = await input({
        message: "Email for SSL (Let's Encrypt):",
        validate: (v) => v?.includes('@') ? true : 'Enter a valid email',
      });

      const dbPassword = crypto.randomBytes(24).toString('base64').replace(/[+/=]/g, '');
      const secretKey = crypto.randomBytes(32).toString('base64');

      const composeContent = this.generateDockerCompose(domain, email, dbPassword, secretKey);

      const rootPath = getRootPath();
      const composePath = resolve(rootPath, 'docker-compose.prod.yml');

      if (existsSync(composePath)) {
        const overwriteCompose = await confirm({
          message: 'docker-compose.prod.yml exists. Overwrite?',
          default: false,
        });
        if (!overwriteCompose) {
          this.log('Skipping docker-compose generation.');
        } else {
          writeFileSync(composePath, composeContent);
          this.log(color.green('✓ Generated docker-compose.prod.yml'));
        }
      } else {
        writeFileSync(composePath, composeContent);
        this.log(color.green('✓ Generated docker-compose.prod.yml'));
      }

      // Generate .env.prod.example
      const envContent = `# Production Environment
DOMAIN=${domain}
DATABASE_PASSWORD=${dbPassword}
DJANGO_SECRET_KEY=${secretKey}
DJANGO_ALLOWED_HOSTS=api.${domain}
STORAGE_BACKEND=local
TASK_BACKEND=celery
TRACING_BACKEND=none
`;
      writeFileSync(resolve(rootPath, '.env.prod.example'), envContent);
      this.log(color.green('✓ Generated .env.prod.example'));
    }

    const setDefault = await confirm({
      message: 'Set VPS as default deployment platform?',
      default: false,
    });

    if (setDefault) {
      await updatePlatformConfig({ defaultPlatform: 'vps' });
    }

    this.log(color.green('\n✅ VPS setup complete!\n'));
    this.log('Commands:');
    this.log(`  ${color.cyan('saas vps deploy')} - Deploy to VPS`);
    this.log(`  ${color.cyan('saas vps status')} - Check status`);
    this.log(`  ${color.cyan('saas vps ssh')}    - SSH into VPS\n`);
  }

  private generateDockerCompose(domain: string, email: string, dbPass: string, secretKey: string): string {
    return `# Docker Compose Production - Generated by SaaS CLI
services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${email}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${dbPass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  backend:
    image: \${BACKEND_IMAGE:-backend:latest}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgres://app:${dbPass}@db:5432/app
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${secretKey}
      DJANGO_ALLOWED_HOSTS: api.${domain}
      STORAGE_BACKEND: local
      TASK_BACKEND: celery
      TRACING_BACKEND: none
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(\`api.${domain}\`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  webapp:
    image: \${WEBAPP_IMAGE:-webapp:latest}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(\`app.${domain}\`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.webapp.loadbalancer.server.port=80"

  celery_worker:
    image: \${BACKEND_IMAGE:-backend:latest}
    restart: unless-stopped
    command: celery -A config worker -l INFO
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://app:${dbPass}@db:5432/app
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${secretKey}
      TASK_BACKEND: celery

  celery_beat:
    image: \${BACKEND_IMAGE:-backend:latest}
    restart: unless-stopped
    command: celery -A config beat -l INFO
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://app:${dbPass}@db:5432/app
      REDIS_URL: redis://redis:6379/0
      DJANGO_SECRET_KEY: ${secretKey}
      TASK_BACKEND: celery

volumes:
  traefik_certs:
  postgres_data:
  redis_data:
`;
  }
}
