# Generated by Django 5.2.8 on 2025-12-24 09:15

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('multitenancy', '0008_alter_tenant_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOUserLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('idp_user_id', models.CharField(help_text='User identifier from the IdP', max_length=512)),
                ('idp_email', models.EmailField(blank=True, default='', max_length=254)),
                ('idp_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('idp_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('idp_groups', models.JSONField(blank=True, default=list)),
                ('idp_raw_attributes', models.JSONField(blank=True, default=dict)),
                ('provisioned_via_jit', models.BooleanField(default=False)),
                ('provisioned_via_scim', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_links',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sso_link',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to='sso.ssouserlink',
                    ),
                ),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSSOConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(help_text='Display name for this SSO connection', max_length=255)),
                (
                    'connection_type',
                    models.CharField(
                        choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], default='saml', max_length=10
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('active', 'Active'),
                            ('inactive', 'Inactive'),
                            ('error', 'Configuration Error'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                (
                    'allowed_domains',
                    models.JSONField(
                        blank=True, default=list, help_text='List of email domains allowed to use this SSO connection'
                    ),
                ),
                (
                    'jit_provisioning_enabled',
                    models.BooleanField(default=True, help_text='Automatically create users on first SSO login'),
                ),
                (
                    'group_role_mapping',
                    models.JSONField(blank=True, default=dict, help_text='Mapping of IdP groups to tenant roles'),
                ),
                ('saml_entity_id', models.CharField(blank=True, default='', max_length=512)),
                ('saml_sso_url', models.URLField(blank=True, default='', max_length=512)),
                (
                    'saml_slo_url',
                    models.URLField(blank=True, default='', help_text='Single Logout URL', max_length=512),
                ),
                (
                    'saml_name_id_format',
                    models.CharField(
                        choices=[
                            ('urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', 'Email Address'),
                            ('urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'Persistent'),
                            ('urn:oasis:names:tc:SAML:2.0:nameid-format:transient', 'Transient'),
                            ('urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified', 'Unspecified'),
                        ],
                        default='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
                        max_length=128,
                    ),
                ),
                (
                    'saml_certificate_arn',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='ARN of the IdP certificate in AWS Secrets Manager',
                        max_length=512,
                    ),
                ),
                (
                    'saml_signing_certificate_arn',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='ARN of our SP signing certificate in AWS Secrets Manager',
                        max_length=512,
                    ),
                ),
                ('saml_want_assertions_signed', models.BooleanField(default=True)),
                ('saml_want_response_signed', models.BooleanField(default=True)),
                (
                    'saml_attribute_mapping',
                    models.JSONField(blank=True, default=dict, help_text='Mapping of SAML attributes to user fields'),
                ),
                ('oidc_issuer', models.URLField(blank=True, default='', max_length=512)),
                ('oidc_client_id', models.CharField(blank=True, default='', max_length=255)),
                (
                    'oidc_client_secret_arn',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='ARN of the client secret in AWS Secrets Manager',
                        max_length=512,
                    ),
                ),
                ('oidc_authorization_endpoint', models.URLField(blank=True, default='', max_length=512)),
                ('oidc_token_endpoint', models.URLField(blank=True, default='', max_length=512)),
                ('oidc_userinfo_endpoint', models.URLField(blank=True, default='', max_length=512)),
                ('oidc_jwks_uri', models.URLField(blank=True, default='', max_length=512)),
                (
                    'oidc_scopes',
                    models.CharField(
                        default='openid email profile', help_text='Space-separated list of OAuth scopes', max_length=512
                    ),
                ),
                (
                    'oidc_claim_mapping',
                    models.JSONField(blank=True, default=dict, help_text='Mapping of OIDC claims to user fields'),
                ),
                ('idp_metadata_xml', models.TextField(blank=True, default='')),
                ('sp_metadata_xml', models.TextField(blank=True, default='')),
                ('metadata_last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sso_connections',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ssouserlink',
            name='sso_connection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='sso.tenantssoconnection'
            ),
        ),
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(help_text='Display name for this token', max_length=255)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('token_prefix', models.CharField(help_text='First 8 chars of token for identification', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scim_tokens',
                        to='multitenancy.tenant',
                    ),
                ),
                (
                    'sso_connection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='scim_tokens',
                        to='sso.tenantssoconnection',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('operating_system', models.CharField(blank=True, default='', max_length=100)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_location', models.CharField(blank=True, default='', max_length=255)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('credential_id', models.CharField(max_length=512, unique=True)),
                ('name', models.CharField(help_text='User-provided name for this passkey', max_length=255)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, default='', max_length=64)),
                ('authenticator_type', models.CharField(blank=True, default='', max_length=50)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('registered_from_ip', models.GenericIPAddressField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='passkeys',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('challenge', models.CharField(max_length=128, unique=True)),
                ('challenge_type', models.CharField(max_length=20)),
                ('user_verification', models.CharField(default='preferred', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='webauthn_challenges',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ssouserlink',
            unique_together={('sso_connection', 'idp_user_id')},
        ),
        migrations.CreateModel(
            name='SSOAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('idp_config_created', 'IdP Configuration Created'),
                            ('idp_config_updated', 'IdP Configuration Updated'),
                            ('idp_config_deleted', 'IdP Configuration Deleted'),
                            ('idp_config_activated', 'IdP Configuration Activated'),
                            ('idp_config_deactivated', 'IdP Configuration Deactivated'),
                            ('sso_login_initiated', 'SSO Login Initiated'),
                            ('sso_login_success', 'SSO Login Success'),
                            ('sso_login_failed', 'SSO Login Failed'),
                            ('sso_logout', 'SSO Logout'),
                            ('user_provisioned', 'User Provisioned via JIT'),
                            ('user_updated', 'User Updated via SSO'),
                            ('group_mapping_applied', 'Group Mapping Applied'),
                            ('scim_user_created', 'SCIM User Created'),
                            ('scim_user_updated', 'SCIM User Updated'),
                            ('scim_user_deleted', 'SCIM User Deleted'),
                            ('scim_group_created', 'SCIM Group Created'),
                            ('scim_group_updated', 'SCIM Group Updated'),
                            ('scim_group_deleted', 'SCIM Group Deleted'),
                            ('session_created', 'Session Created'),
                            ('session_revoked', 'Session Revoked'),
                            ('device_registered', 'Device Registered'),
                            ('device_removed', 'Device Removed'),
                            ('passkey_registered', 'Passkey Registered'),
                            ('passkey_removed', 'Passkey Removed'),
                            ('passkey_auth_success', 'Passkey Auth Success'),
                            ('passkey_auth_failed', 'Passkey Auth Failed'),
                        ],
                        max_length=50,
                    ),
                ),
                ('event_description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                (
                    'tenant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sso_audit_logs',
                        to='multitenancy.tenant',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sso_audit_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sso_connection',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to='sso.tenantssoconnection',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['tenant', '-created_at'], name='sso_ssoaudi_tenant__12fa54_idx'),
                    models.Index(fields=['user', '-created_at'], name='sso_ssoaudi_user_id_f0d9ef_idx'),
                    models.Index(fields=['event_type', '-created_at'], name='sso_ssoaudi_event_t_ee1fad_idx'),
                ],
            },
        ),
    ]
