# Generated by Django 5.2.8 on 2025-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantssoconnection',
            name='oidc_client_secret',
            field=models.CharField(
                blank=True, default='', help_text='Client secret - for local development', max_length=512
            ),
        ),
        migrations.AddField(
            model_name='tenantssoconnection',
            name='saml_certificate',
            field=models.TextField(
                blank=True, default='', help_text='IdP X.509 certificate (PEM format) - for local development'
            ),
        ),
    ]
