# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sso', '0003_alter_ssoauditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantssoconnection',
            name='enforce_sso',
            field=models.BooleanField(
                default=False,
                help_text='When enabled, users from allowed domains must use SSO to access this tenant. Password login will not grant access.',
            ),
        ),
        migrations.AlterField(
            model_name='ssoauditlog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('idp_config_created', 'IdP Configuration Created'),
                    ('idp_config_updated', 'IdP Configuration Updated'),
                    ('idp_config_deleted', 'IdP Configuration Deleted'),
                    ('idp_config_activated', 'IdP Configuration Activated'),
                    ('idp_config_deactivated', 'IdP Configuration Deactivated'),
                    ('sso_login_initiated', 'SSO Login Initiated'),
                    ('sso_login_success', 'SSO Login Success'),
                    ('sso_login_failed', 'SSO Login Failed'),
                    ('sso_logout', 'SSO Logout'),
                    ('user_provisioned', 'User Provisioned via JIT'),
                    ('user_updated', 'User Updated via SSO'),
                    ('group_mapping_applied', 'Group Mapping Applied'),
                    ('scim_user_created', 'SCIM User Created'),
                    ('scim_user_updated', 'SCIM User Updated'),
                    ('scim_user_deleted', 'SCIM User Deleted'),
                    ('scim_group_created', 'SCIM Group Created'),
                    ('scim_group_updated', 'SCIM Group Updated'),
                    ('scim_group_deleted', 'SCIM Group Deleted'),
                    ('sso_enforce_bypass', 'SSO Enforcement Bypassed (Break-glass)'),
                    ('session_created', 'Session Created'),
                    ('session_revoked', 'Session Revoked'),
                    ('device_registered', 'Device Registered'),
                    ('device_removed', 'Device Removed'),
                    ('passkey_registered', 'Passkey Registered'),
                    ('passkey_removed', 'Passkey Removed'),
                    ('passkey_auth_success', 'Passkey Auth Success'),
                    ('passkey_auth_failed', 'Passkey Auth Failed'),
                    ('passkey_clone_detected', 'Passkey Clone Detected'),
                    ('security_anomaly', 'Security Anomaly Detected'),
                ],
                max_length=50,
            ),
        ),
    ]
