apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
