# Generated by Django 3.1.6 on 2021-02-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fields', models.JSONField(default={})),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
