# Generated by Django 3.2.5 on 2021-07-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0008_2_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.price',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djstripe.product',),
        ),
    ]
