# Generated by Django 4.2 on 2024-03-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0002_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='invitation_accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='invitee_email_address',
            field=models.EmailField(
                db_collation='case_insensitive', default='', max_length=255, verbose_name='invitee email address'
            ),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='id',
            field=hashid_field.field.HashidAutoField(
                alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                min_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tenant_memberships',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('user', 'tenant'),
                name='unique_non_null_user_and_tenant',
            ),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(
                condition=models.Q(('invitee_email_address__exact', ''), _negated=True),
                fields=('invitee_email_address', 'tenant'),
                name='unique_non_null_user_and_invitee_email_address',
            ),
        ),
    ]
