# Generated by Django 4.2 on 2024-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0003_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='invitee_email_address',
            field=models.EmailField(
                db_collation='case_insensitive', default='', max_length=255, verbose_name='invitee email address'
            ),
        ),
    ]
