# Generated by Django 4.2 on 2024-03-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0004_auto_20240318_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_email',
            field=models.EmailField(
                blank=True, db_collation='case_insensitive', max_length=255, verbose_name='billing email address'
            ),
        ),
    ]
