# Generated by Django 4.2 on 2024-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0005_tenant_billing_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(
                choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MEMBER', 'Member')], default='OWNER'
            ),
        ),
    ]
