# Generated by Django 5.2.8 on 2025-12-24 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0007_tenantmembership_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='tenants',
                through='multitenancy.TenantMembership',
                through_fields=('tenant', 'user'),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
