# Generated by Django 5.2.9 on 2026-01-09 08:36

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0008_alter_tenant_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='action_logging_enabled',
            field=models.BooleanField(default=False, help_text='Enable action logging for this organization'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'action_type',
                    models.CharField(
                        choices=[
                            ('CREATE', 'Create'),
                            ('UPDATE', 'Update'),
                            ('DELETE', 'Delete'),
                            ('SETTINGS_CHANGE', 'Settings Change'),
                            ('IMPORT', 'Import'),
                            ('SYNC', 'Sync'),
                            ('BULK_DELETE', 'Bulk Delete'),
                        ],
                        help_text='Type of action performed',
                        max_length=20,
                    ),
                ),
                (
                    'entity_type',
                    models.CharField(help_text='Type of entity affected (e.g., client, project, user)', max_length=50),
                ),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                (
                    'entity_name',
                    models.CharField(
                        blank=True, help_text='Human-readable name of the entity for display', max_length=255
                    ),
                ),
                (
                    'actor_type',
                    models.CharField(
                        choices=[
                            ('USER', 'User'),
                            ('SYSTEM:sync', 'System (Sync)'),
                            ('SYSTEM:import', 'System (Import)'),
                            ('SYSTEM:scheduled_task', 'System (Scheduled Task)'),
                            ('SYSTEM:migration', 'System (Migration)'),
                        ],
                        default='USER',
                        help_text='Type of actor that performed the action',
                        max_length=30,
                    ),
                ),
                (
                    'actor_email',
                    models.EmailField(
                        blank=True, help_text='Email of the actor (stored for historical reference)', max_length=254
                    ),
                ),
                ('changes', models.JSONField(default=dict, help_text='Field-level changes with old and new values')),
                (
                    'metadata',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional context (import session ID, source system, etc.)',
                    ),
                ),
                (
                    'actor_user',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who performed the action (null for system actions)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='action_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='action_logs',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['-created_at'], name='multitenanc_created_72aa3a_idx'),
                    models.Index(fields=['tenant', '-created_at'], name='multitenanc_tenant__de7c42_idx'),
                    models.Index(fields=['entity_type'], name='multitenanc_entity__bed28d_idx'),
                    models.Index(fields=['action_type'], name='multitenanc_action__7a07a4_idx'),
                    models.Index(fields=['actor_user'], name='multitenanc_actor_u_8fe9d6_idx'),
                ],
            },
        ),
    ]
