# Generated by Django 5.2.9 on 2026-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0010_add_action_log_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('CREATE', 'Create'),
                    ('UPDATE', 'Update'),
                    ('DELETE', 'Delete'),
                    ('SETTINGS_CHANGE', 'Settings Change'),
                    ('IMPORT', 'Import'),
                    ('SYNC', 'Sync'),
                    ('BULK_DELETE', 'Bulk Delete'),
                    ('BULK_UPDATE', 'Bulk Update'),
                    ('ACTIVATE', 'Activate'),
                    ('DEACTIVATE', 'Deactivate'),
                    ('REVOKE', 'Revoke'),
                ],
                help_text='Type of action performed',
                max_length=20,
            ),
        ),
    ]
