# Generated by Django 5.2.9 on 2026-01-09 11:39

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0011_alter_actionlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text="Unique permission code (e.g., 'dashboard.projects.edit')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ('name', models.CharField(help_text='Human-readable name for display', max_length=100)),
                (
                    'description',
                    models.TextField(blank=True, help_text='Detailed description of what this permission allows'),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('organization', 'Organization'),
                            ('members', 'Members'),
                            ('security', 'Security'),
                            ('billing', 'Billing'),
                            ('dashboard', 'Dashboard'),
                        ],
                        help_text='Category for grouping in UI',
                        max_length=50,
                    ),
                ),
                ('is_system', models.BooleanField(default=True, help_text='System permissions cannot be deleted')),
                ('sort_order', models.IntegerField(default=0, help_text='Order within category for UI display')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(help_text='Display name of the role', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the role's purpose")),
                (
                    'system_role_type',
                    models.CharField(
                        blank=True,
                        choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MEMBER', 'Member')],
                        help_text='If set, this is a system template role',
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        choices=[
                            ('blue', 'Blue'),
                            ('green', 'Green'),
                            ('red', 'Red'),
                            ('yellow', 'Yellow'),
                            ('purple', 'Purple'),
                            ('orange', 'Orange'),
                            ('pink', 'Pink'),
                            ('teal', 'Teal'),
                            ('gray', 'Gray'),
                        ],
                        default='blue',
                        help_text='Color for UI display',
                        max_length=20,
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_roles',
                        to='multitenancy.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Organization Role',
                'verbose_name_plural': 'Organization Roles',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRolePermission',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='role_permissions',
                        to='multitenancy.organizationrole',
                    ),
                ),
                (
                    'permission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='permission_roles',
                        to='multitenancy.permission',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(
                blank=True,
                related_name='roles',
                through='multitenancy.OrganizationRolePermission',
                to='multitenancy.permission',
            ),
        ),
        migrations.CreateModel(
            name='TenantMembershipRole',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                (
                    'assigned_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_membership_roles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'membership',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='membership_roles',
                        to='multitenancy.tenantmembership',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='member_assignments',
                        to='multitenancy.organizationrole',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Membership Role',
                'verbose_name_plural': 'Membership Roles',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_org_role_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(
                condition=models.Q(('system_role_type__isnull', False)),
                fields=('tenant', 'system_role_type'),
                name='unique_system_role_per_tenant',
            ),
        ),
        migrations.AddConstraint(
            model_name='tenantmembershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_membership_role'),
        ),
    ]
