# Generated by Django 5.2.9 on 2026-01-09 11:39

from django.db import migrations


def seed_permissions(apps, schema_editor):
    """Seed all permissions into the database."""
    from apps.multitenancy.permissions import PERMISSIONS
    
    Permission = apps.get_model('multitenancy', 'Permission')
    
    for perm_def in PERMISSIONS:
        Permission.objects.update_or_create(
            code=perm_def.code,
            defaults={
                'name': perm_def.name,
                'description': perm_def.description,
                'category': perm_def.category,
                'sort_order': perm_def.sort_order,
                'is_system': True,
            }
        )


def create_system_roles_for_existing_tenants(apps, schema_editor):
    """Create system roles for all existing tenants."""
    from apps.multitenancy.permissions import ROLE_TEMPLATE_PERMISSIONS
    from apps.multitenancy.constants import SystemRoleType, RoleColor
    
    Tenant = apps.get_model('multitenancy', 'Tenant')
    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')
    Permission = apps.get_model('multitenancy', 'Permission')
    
    role_configs = [
        {
            'system_role_type': SystemRoleType.OWNER,
            'name': 'Owner',
            'description': 'Full access to all organization features',
            'color': RoleColor.PURPLE,
        },
        {
            'system_role_type': SystemRoleType.ADMIN,
            'name': 'Administrator',
            'description': 'Manage organization settings and members',
            'color': RoleColor.BLUE,
        },
        {
            'system_role_type': SystemRoleType.MEMBER,
            'name': 'Member',
            'description': 'View access to organization data',
            'color': RoleColor.GREEN,
        },
    ]
    
    for tenant in Tenant.objects.iterator(chunk_size=100):
        for config in role_configs:
            role, created = OrganizationRole.objects.get_or_create(
                tenant=tenant,
                system_role_type=config['system_role_type'],
                defaults={
                    'name': config['name'],
                    'description': config['description'],
                    'color': config['color'],
                }
            )
            
            # Assign permissions based on template
            permission_codes = ROLE_TEMPLATE_PERMISSIONS.get(config['system_role_type'])
            if permission_codes is None:
                # OWNER gets all permissions
                permissions = Permission.objects.all()
            else:
                permissions = Permission.objects.filter(code__in=permission_codes)
            
            for permission in permissions:
                OrganizationRolePermission.objects.get_or_create(
                    role=role,
                    permission=permission,
                )


def migrate_existing_memberships_to_roles(apps, schema_editor):
    """
    Migrate existing TenantMembership.role to TenantMembershipRole.
    Maps legacy OWNER/ADMIN/MEMBER to the corresponding system roles.
    """
    from apps.multitenancy.constants import TenantUserRole, SystemRoleType
    
    TenantMembership = apps.get_model('multitenancy', 'TenantMembership')
    TenantMembershipRole = apps.get_model('multitenancy', 'TenantMembershipRole')
    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    
    # Map legacy roles to system role types
    legacy_to_system = {
        TenantUserRole.OWNER: SystemRoleType.OWNER,
        TenantUserRole.ADMIN: SystemRoleType.ADMIN,
        TenantUserRole.MEMBER: SystemRoleType.MEMBER,
    }
    
    for membership in TenantMembership.objects.select_related('tenant').iterator(chunk_size=100):
        system_role_type = legacy_to_system.get(membership.role)
        if system_role_type:
            org_role = OrganizationRole.objects.filter(
                tenant=membership.tenant,
                system_role_type=system_role_type,
            ).first()
            
            if org_role:
                TenantMembershipRole.objects.get_or_create(
                    membership=membership,
                    role=org_role,
                )


def reverse_seed_permissions(apps, schema_editor):
    """Remove all seeded permissions."""
    Permission = apps.get_model('multitenancy', 'Permission')
    Permission.objects.filter(is_system=True).delete()


def reverse_system_roles(apps, schema_editor):
    """Remove all system roles."""
    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    OrganizationRole.objects.filter(system_role_type__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0012_rbac_models'),
    ]

    operations = [
        migrations.RunPython(seed_permissions, reverse_seed_permissions),
        migrations.RunPython(create_system_roles_for_existing_tenants, reverse_system_roles),
        migrations.RunPython(migrate_existing_memberships_to_roles, migrations.RunPython.noop),
    ]
