# Generated by Django
"""
Add Features category permissions and update existing roles.
"""

from django.db import migrations


def seed_features_permissions(apps, schema_editor):
    """Add features permissions for AI, Documents, Content, and CRUD."""
    Permission = apps.get_model('multitenancy', 'Permission')
    
    # Get or create FEATURES category permissions
    features_permissions = [
        {
            'code': 'features.ai.use',
            'name': 'Use AI Features',
            'description': 'Access and use OpenAI integration and AI-powered features',
            'category': 'features',
            'sort_order': 10,
        },
        {
            'code': 'features.documents.view',
            'name': 'View Documents',
            'description': 'View uploaded documents',
            'category': 'features',
            'sort_order': 20,
        },
        {
            'code': 'features.documents.manage',
            'name': 'Manage Documents',
            'description': 'Upload, edit, and delete documents',
            'category': 'features',
            'sort_order': 30,
        },
        {
            'code': 'features.content.view',
            'name': 'View Content Items',
            'description': 'View content items from CMS',
            'category': 'features',
            'sort_order': 40,
        },
        {
            'code': 'features.crud.view',
            'name': 'View CRUD Demo Items',
            'description': 'View CRUD demo items',
            'category': 'features',
            'sort_order': 50,
        },
        {
            'code': 'features.crud.manage',
            'name': 'Manage CRUD Demo Items',
            'description': 'Create, edit, and delete CRUD demo items',
            'category': 'features',
            'sort_order': 60,
        },
    ]
    
    created_permissions = []
    for perm_data in features_permissions:
        perm, created = Permission.objects.update_or_create(
            code=perm_data['code'],
            defaults={
                'name': perm_data['name'],
                'description': perm_data['description'],
                'category': perm_data['category'],
                'sort_order': perm_data['sort_order'],
                'is_system': True,
            }
        )
        created_permissions.append(perm)
    
    # Update existing system roles to include feature permissions
    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')
    
    # Get feature permission objects
    features_view_perms = Permission.objects.filter(code__in=[
        'features.ai.use',
        'features.documents.view',
        'features.content.view',
        'features.crud.view',
    ])
    features_all_perms = Permission.objects.filter(code__startswith='features.')
    
    # Update OWNER roles - get all feature permissions
    owner_roles = OrganizationRole.objects.filter(system_role_type='OWNER')
    for role in owner_roles:
        for perm in features_all_perms:
            OrganizationRolePermission.objects.get_or_create(
                role=role,
                permission=perm,
            )
    
    # Update ADMIN roles - get all feature permissions
    admin_roles = OrganizationRole.objects.filter(system_role_type='ADMIN')
    for role in admin_roles:
        for perm in features_all_perms:
            OrganizationRolePermission.objects.get_or_create(
                role=role,
                permission=perm,
            )
    
    # Update MEMBER roles - get view-only feature permissions
    member_roles = OrganizationRole.objects.filter(system_role_type='MEMBER')
    for role in member_roles:
        for perm in features_view_perms:
            OrganizationRolePermission.objects.get_or_create(
                role=role,
                permission=perm,
            )


def reverse_migration(apps, schema_editor):
    """Remove features permissions."""
    Permission = apps.get_model('multitenancy', 'Permission')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')
    
    # Get feature permissions
    features_perms = Permission.objects.filter(code__startswith='features.')
    
    # Remove role-permission associations
    OrganizationRolePermission.objects.filter(permission__in=features_perms).delete()
    
    # Remove permissions
    features_perms.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0013_seed_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_features_permissions, reverse_migration),
    ]
