# Generated by Django
"""
Rename dashboard.* permissions to management.* for Management Dashboard,
and add proper dashboard.view permission for main app Dashboard.
"""

from django.db import migrations


PERMISSION_RENAMES = []


def rename_permissions(apps, schema_editor):
    """
    Rename dashboard.* permissions to management.* and add management.view.
    
    This migration is idempotent to handle cases where:
    - Permissions were seeded from current code (management.* already exists)
    - Running on fresh database vs existing database
    """
    Permission = apps.get_model('multitenancy', 'Permission')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')
    
    # Check what already exists
    management_view_exists = Permission.objects.filter(code='management.view').exists()
    dashboard_view_exists = Permission.objects.filter(code='dashboard.view').exists()
    
    # Handle dashboard.view -> management.view rename
    if dashboard_view_exists and not management_view_exists:
        # Standard case: rename dashboard.view to management.view
        dashboard_view = Permission.objects.get(code='dashboard.view')
        dashboard_view.code = 'management.view'
        dashboard_view.name = 'View Management Dashboard'
        dashboard_view.description = 'Access the management dashboard overview'
        dashboard_view.category = 'management'
        dashboard_view.save()
    elif management_view_exists:
        # management.view already exists (seeded from current code)
        # Just ensure it has the correct attributes
        Permission.objects.filter(code='management.view').update(
            name='View Management Dashboard',
            description='Access the management dashboard overview',
            category='management',
        )
        # If old dashboard.view also exists (shouldn't happen but be safe),
        # delete it since we'll create the new one below
        if dashboard_view_exists:
            # Check if it's the old "management" dashboard.view or new "main app" dashboard.view
            old_dash = Permission.objects.filter(code='dashboard.view').first()
            if old_dash and old_dash.category != 'dashboard':
                old_dash.delete()
    
    # Rename other permissions (only if they exist and target doesn't)
    for old_code, new_code in PERMISSION_RENAMES:
        old_exists = Permission.objects.filter(code=old_code).exists()
        new_exists = Permission.objects.filter(code=new_code).exists()
        
        if old_exists and not new_exists:
            # Standard case: rename
            perm = Permission.objects.get(code=old_code)
            perm.code = new_code
            perm.category = 'management'
            if 'Dashboard' in perm.name:
                perm.name = perm.name.replace('Dashboard', 'Management')
            perm.save()
        elif new_exists:
            # Already exists (seeded from current code), ensure correct category
            Permission.objects.filter(code=new_code).update(category='management')
            # Delete old if it still exists
            if old_exists:
                Permission.objects.filter(code=old_code).delete()
    
    # Create the new dashboard.view permission for main app Dashboard
    Permission.objects.update_or_create(
        code='dashboard.view',
        defaults={
            'name': 'View Dashboard',
            'description': 'Access the main app dashboard/home page',
            'category': 'dashboard',
            'sort_order': 10,
            'is_system': True,
        }
    )
    
    # Assign dashboard.view to all existing roles that have management.view
    mgmt_view = Permission.objects.filter(code='management.view').first()
    dash_view = Permission.objects.filter(code='dashboard.view').first()
    
    if mgmt_view and dash_view:
        # Get all roles that have management.view and give them dashboard.view too
        role_perms_with_mgmt = OrganizationRolePermission.objects.filter(permission=mgmt_view)
        for role_perm in role_perms_with_mgmt:
            OrganizationRolePermission.objects.get_or_create(
                role=role_perm.role,
                permission=dash_view,
            )


def reverse_rename(apps, schema_editor):
    """Reverse the rename - convert management.* back to dashboard.*."""
    Permission = apps.get_model('multitenancy', 'Permission')
    
    # Delete the new dashboard.view
    Permission.objects.filter(code='dashboard.view', category='dashboard').delete()
    
    # Rename management.view back to dashboard.view
    try:
        mgmt_view = Permission.objects.get(code='management.view')
        mgmt_view.code = 'dashboard.view'
        mgmt_view.name = 'View Dashboard'
        mgmt_view.description = 'Access the management dashboard overview'
        mgmt_view.category = 'dashboard'
        mgmt_view.save()
    except Permission.DoesNotExist:
        pass
    
    # Rename other permissions back
    for old_code, new_code in PERMISSION_RENAMES:
        try:
            perm = Permission.objects.get(code=new_code)
            perm.code = old_code
            perm.category = 'dashboard'
            if 'Management' in perm.name:
                perm.name = perm.name.replace('Management', 'Dashboard')
            perm.save()
        except Permission.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0014_add_features_permissions'),
    ]

    operations = [
        migrations.RunPython(rename_permissions, reverse_rename),
    ]
