# Generated by Django 5.2.9 on 2026-01-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0015_rename_dashboard_to_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(
                choices=[
                    ('organization', 'Organization'),
                    ('members', 'Members'),
                    ('security', 'Security'),
                    ('billing', 'Billing'),
                    ('features', 'Features'),
                    ('dashboard', 'Dashboard'),
                    ('management', 'Management Dashboard'),
                ],
                help_text='Category for grouping in UI',
                max_length=50,
            ),
        ),
    ]
