# Generated by Django 5.2.10 on 2026-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0020_add_costrates_view_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationrole',
            name='unique_system_role_per_tenant',
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='system_role_type',
            field=models.CharField(
                blank=True,
                choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MEMBER', 'Member')],
                default='',
                help_text='If set, this is a system template role',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(
                condition=models.Q(('system_role_type__gt', '')),
                fields=('tenant', 'system_role_type'),
                name='unique_system_role_per_tenant',
            ),
        ),
    ]
