# Generated by Django 5.2.11 on 2026-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('multitenancy', '0022_rbac_backfill_default_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(
                help_text='Category for grouping in UI (multitenancy enum or app-defined)', max_length=50
            ),
        ),
    ]
