# Generated by Django 5.2.9 on 2026-01-06 01:50

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='original',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN(),
                upload_to=common.storages.UniqueFilePathGenerator('avatars'),
            ),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='thumbnail',
            field=models.ImageField(
                null=True,
                storage=common.storages.PublicS3Boto3StorageWithCDN(),
                upload_to=common.storages.UniqueFilePathGenerator('avatars/thumbnails'),
            ),
        ),
    ]
