# Generated by Django 3.1.7 on 2021-07-16 16:03

import os

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_superuser(apps, schema_editor):
    if "ADMIN_EMAIL" in os.environ and "ADMIN_DEFAULT_PASSWORD" in os.environ :
        User = apps.get_model('users', 'User')
        user = User(email=os.getenv('ADMIN_EMAIL'), is_superuser=True)
        user.password = make_password(os.getenv('ADMIN_DEFAULT_PASSWORD'))
        user.save()
        return user


def remove_default_superuser(apps, schema_editor):
    if "ADMIN_EMAIL" in os.environ :
        User = apps.get_model('users', 'User')
        return User.objects.get(email=os.getenv('ADMIN_EMAIL')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_default_groups'),
    ]

    operations = [migrations.RunPython(create_default_superuser, remove_default_superuser)]
