# Generated by Django 4.0.8 on 2023-04-12 12:35
from django.contrib.postgres.operations import CreateCollation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_otp_auth_url_alter_user_otp_base32'),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                db_collation='case_insensitive', max_length=255, unique=True, verbose_name='email address'
            ),
        ),
    ]
