# Generated by Django - Initial migration for translations app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    help_text="Locale code (e.g., 'en', 'pl', 'de', 'en-US')",
                    max_length=10,
                    unique=True,
                    validators=[django.core.validators.RegexValidator(
                        message="Locale code must be in format 'xx' or 'xx-XX' (e.g., 'en', 'en-US', 'pl')",
                        regex='^[a-z]{2}(-[A-Z]{2})?$'
                    )]
                )),
                ('name', models.CharField(help_text="Language name in English (e.g., 'English', 'Polish')", max_length=100)),
                ('native_name', models.CharField(help_text="Language name in native language (e.g., 'English', 'Polski')", max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default/fallback locale')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this locale is available to users')),
                ('rtl', models.BooleanField(default=False, help_text='Right-to-left language (e.g., Arabic, Hebrew)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Locale',
                'verbose_name_plural': 'Locales',
                'ordering': ['-is_default', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(
                    db_index=True,
                    help_text="The unique message ID from the codebase (e.g., 'Home / dashboard link')",
                    max_length=512,
                    unique=True
                )),
                ('default_message', models.TextField(help_text='The English default message from the code')),
                ('description', models.TextField(blank=True, help_text='Context or description to help translators understand the message')),
                ('source_file', models.CharField(blank=True, help_text='File where this key was found (for reference)', max_length=512)),
                ('is_deprecated', models.BooleanField(db_index=True, default=False, help_text='Whether this key is no longer in use in the codebase')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Translation Key',
                'verbose_name_plural': 'Translation Keys',
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='translationkey',
            index=models.Index(fields=['is_deprecated', 'key'], name='translation_is_depr_e1c0c8_idx'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='The translated text')),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('review', 'Needs Review'),
                        ('approved', 'Approved'),
                        ('published', 'Published')
                    ],
                    db_index=True,
                    default='draft',
                    max_length=20
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='translations.translationkey')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='translations.locale')),
                ('translated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key__key', 'locale__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=['key', 'locale'], name='unique_translation_key_locale'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['locale', 'status'], name='translation_locale__5b6f6e_idx'),
        ),
        migrations.CreateModel(
            name='TranslationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., 'v20231215120000-abc123')", max_length=50)),
                ('s3_key', models.CharField(help_text='S3 object key for the versioned JSON file', max_length=512)),
                ('translation_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active version')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='translations.locale')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Version',
                'verbose_name_plural': 'Translation Versions',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='translationversion',
            constraint=models.UniqueConstraint(fields=['locale', 'version'], name='unique_version_per_locale'),
        ),
    ]

