# Generated by Django 5.2.9 on 2025-12-29 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('translations', '0003_aitranslationjob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='unique_translation_key_locale',
        ),
        migrations.RemoveConstraint(
            model_name='translationversion',
            name='unique_version_per_locale',
        ),
        migrations.RenameIndex(
            model_name='translation',
            new_name='translation_locale__ebc0fa_idx',
            old_name='translation_locale__5b6f6e_idx',
        ),
        migrations.RenameIndex(
            model_name='translationkey',
            new_name='translation_is_depr_5e60ef_idx',
            old_name='translation_is_depr_e1c0c8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('key', 'locale')},
        ),
        migrations.AlterUniqueTogether(
            name='translationversion',
            unique_together={('locale', 'version')},
        ),
    ]
