# Generated by Django 5.2.10 on 2026-02-12 09:39

import django.core.validators
import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models

def add_backup_permissions(apps, schema_editor):
    """Add backup management permissions (from 0007)."""
    from apps.multitenancy.permissions import get_all_permissions

    Permission = apps.get_model('multitenancy', 'Permission')
    backup_permission_codes = ['backup.view', 'backup.manage']
    for perm_def in get_all_permissions():
        if perm_def.code in backup_permission_codes:
            category_value = getattr(perm_def.category, 'value', perm_def.category)
            Permission.objects.update_or_create(
                code=perm_def.code,
                defaults={
                    'name': perm_def.name,
                    'description': perm_def.description,
                    'category': category_value,
                    'sort_order': perm_def.sort_order,
                    'is_system': True,
                }
            )


def update_system_roles_with_backup_permissions(apps, schema_editor):
    """Assign backup permissions to system roles (from 0007)."""
    from apps.multitenancy.constants import SystemRoleType

    OrganizationRole = apps.get_model('multitenancy', 'OrganizationRole')
    OrganizationRolePermission = apps.get_model('multitenancy', 'OrganizationRolePermission')
    Permission = apps.get_model('multitenancy', 'Permission')
    backup_view_perm = Permission.objects.filter(code='backup.view').first()
    backup_manage_perm = Permission.objects.filter(code='backup.manage').first()
    if not backup_view_perm or not backup_manage_perm:
        return
    for role in OrganizationRole.objects.filter(system_role_type=SystemRoleType.OWNER):
        OrganizationRolePermission.objects.get_or_create(role=role, permission=backup_view_perm)
        OrganizationRolePermission.objects.get_or_create(role=role, permission=backup_manage_perm)
    for role in OrganizationRole.objects.filter(system_role_type=SystemRoleType.ADMIN):
        OrganizationRolePermission.objects.get_or_create(role=role, permission=backup_view_perm)
        OrganizationRolePermission.objects.get_or_create(role=role, permission=backup_manage_perm)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0001_initial'),
        ('multitenancy', '0012_rbac_models'),
    ]

    # No 'replaces' - this is the only migration; having replaces=[..., '0001_initial'] made Django skip applying it.

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether periodic backups are enabled for this tenant')),
                ('backup_interval_hours', models.PositiveIntegerField(default=24, help_text='Interval between backups in hours (minimum 1 hour)', validators=[django.core.validators.MinValueValidator(1)])),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Number of days to retain backup files (minimum 1 day)', validators=[django.core.validators.MinValueValidator(1)])),
                ('email_recipients', models.JSONField(default=list, help_text='List of user IDs to receive email notifications when backups are ready')),
                ('selected_modules', models.JSONField(default=list, help_text="List of module IDs to include in backups (e.g., ['financial_data', 'user_management'])")),
                ('selected_models', models.JSONField(default=list, help_text="Optional: Specific models to include (format: 'app_label.ModelName'). If empty, all models in selected_modules are included.")),
                ('excluded_models', models.JSONField(default=list, help_text="Optional: Specific models to exclude from backup (format: 'app_label.ModelName')")),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backupconfig_set', to='multitenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configurations',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(blank=True, help_text='Storage path to the backup file', max_length=500)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Size of the backup file in bytes', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the backup', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if backup failed')),
                ('model_counts', models.JSONField(default=dict, help_text='Count of records per model type in this backup')),
                ('backup_config', models.ForeignKey(blank=True, help_text='The backup configuration that triggered this backup', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='backup.backupconfig')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backuprecord_set', to='multitenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='backupconfig',
            constraint=models.UniqueConstraint(fields=('tenant',), name='backup_backupconfig_unique_tenant'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Whether this backup file is encrypted at rest'),
        ),
        migrations.RemoveConstraint(
            model_name='backupconfig',
            name='backup_backupconfig_unique_tenant',
        ),
        migrations.AlterField(
            model_name='backupconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='multitenancy.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='backuprecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='multitenancy.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='backupconfig',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_backup_config_per_tenant'),
        ),
        migrations.CreateModel(
            name='RestoreRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current status of the restoration', max_length=30)),
                ('conflict_strategy', models.CharField(choices=[('SKIP', 'Skip existing records'), ('UPDATE', 'Update existing records'), ('FAIL', 'Fail on conflicts')], help_text='Strategy used for handling conflicting records during restore', max_length=20)),
                ('model_counts', models.JSONField(default=dict, help_text='Detailed counts per model: {ModelName: {created: N, updated: N, skipped: N, failed: N}}')),
                ('error_message', models.TextField(blank=True, help_text='Error message if restoration failed')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the restoration started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the restoration completed or failed', null=True)),
                ('backup_record', models.ForeignKey(help_text='The backup record that was restored', on_delete=django.db.models.deletion.CASCADE, related_name='restore_records', to='backup.backuprecord')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='multitenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Restore Record',
                'verbose_name_plural': 'Restore Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(add_backup_permissions, migrations.RunPython.noop),
        migrations.RunPython(update_system_roles_with_backup_permissions, migrations.RunPython.noop),
    ]
