# Generated by Django 5.2.10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTenantEncryptionKey',
            fields=[
                ('tenant', models.OneToOneField(
                    help_text='Tenant this encryption key belongs to',
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='backup_encryption_key',
                    serialize=False,
                    to='multitenancy.tenant',
                )),
                ('encrypted_key', models.TextField(
                    help_text='Fernet-encrypted 32-byte AES key (base64). Encrypted with BACKUP_MASTER_KEY.',
                )),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    help_text='When the key was last created or rotated',
                )),
            ],
            options={
                'verbose_name': 'Backup tenant encryption key',
                'verbose_name_plural': 'Backup tenant encryption keys',
            },
        ),
    ]
