# Generated by Django 5.2.11 on 2026-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backup', '0002_backuptenantencryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restorerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
