name: "Deploy to production"

concurrency: Production

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - uses: ./.github/workflows/actions/deploy
        with:
          environment-name: 'saas-prod'
          artifacts-s3-bucket: '${{ secrets.SB_CI_ARTIFACTS_BUCKET }}'
          role-arn: '${{ secrets.SB_CI_ROLE_ARN }}'
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
